from django.urls import path
from .views import *

urlpatterns = [
    path('', Login, name="login"),
    path('login/', Login, name="login"),
    path('logout/', LogOut, name="logout"),
    path('login/auth/', Login_Auth, name="login-auth"),
    path('hisobot/', Index, name='hisobot'),
    path('workers/', Workers, name='workers'),
    path('workers/add', Add_Worker, name='workers-add'),
    path('pupils/', Pupils_All, name='pupils_all'),
    path('parents_function/', Parents_function, name="parents"),
    path('tasks/', All_Tasks, name='tasks_all'),
    path('parents/', All_Parents, name='parents-all'),
    path('pupils/test', Pupil_Test),
    path('payment/create/pupil/<int:pk>', Payment_Pupil, name='payment-pupil'),
    path('pupil/delete/<int:pk>/', Delete_Pupil, name='delete-pupil'),
    path('pupil/edit/', Edit_Pupil, name='edit-pupil'),
    path('pupil/filter/', Filter_Pupil, name='filter-pupil'),
    path('groups/filter/', Filter_groups, name='filter-groups'),
    path('groups/add/', Add_groups, name='add-groups'),
    path('teacher/filter', Filter_Teacher, name='filter-teacher'),
    path('delete/teachers/<int:pk>/', Delete_teachers, name="delete-teachers"),
    path('delete/groups/<int:pk>/', Delete_groups, name="delete-groups"),
    path('delete/parents/<int:pk>/', Delete_Parents, name="delete-parents"),
    path('delete/worker/<int:pk>/', Delete_worker, name="delete-worker"),
    path('edit-teachers/', Edit_teachers, name="edit-teachers"),
    path('edit-groups/', Edit_Groups, name="edit-groups"),
    path('edit-parents/', Edit_Parents, name="edit-parents"),
    path('edit-worker/', Edit_Worker, name="edit-worker"),
    path('payments/history/<int:pk>/', Payments_History, name='payments-history'),
    path('payments/history/all/', Payments_All, name='payments-all'),
    path('pupils/search/', Search_Pupil, name='search-pupil'),
    path('teacher/search/', Search_Teacher, name="search-teacher"),
    path('groups/search/', Search_Group, name="search-groups"),
    path('payments/search/', Search_Payments, name="search-payments"),
    path('parents/search/', Search_Parents, name="search-parents"),
    path('workers/search/', Search_Worker, name="search-worker"),
    path('debtors/', Debtors, name="debtors"),
    path('teachers/', Teachers, name="teachers"),
    path('groups/', Groups, name="groups"),
    path('notification/add/<int:pk>', Add_Notification, name='add-notification'),
    path('notification/send/', Send_Notification, name='send-notification'),
    path('pupils/add/', Add_Pupil, name='add-pupil'),
    path('teachers/add/', Add_teacher, name='add-teacher'),
    path('pupils/payment/check/', Check_Payments_Monthly, name='check-payments'),
    path('teachers/sallary/pay/<int:pk>/', Pay_Sallary, name='pay-sallary'),
    path('send/message/parent/<int:pk>/', Send_Message_Parent, name="send-message-parent"),
    path('get/result/task/<int:pk>/', Get_Task_Result, name="get-result"),
    path('accept/task/', Accept_Task, name='accept-task'),
    path('cancel/task/', Cancel_Task, name='cancel-task'),
    path('task/add/', Add_Task, name='add-task'),
    path('add/parents/', Add_Parents, name="add-parents"),
    path('time-tables/', TimeTables, name='time-tables'),
    path('attendance/<int:pk>/', Attendance, name='attendance'),
    path('davomat/<int:pk>/', Davomat, name='davomat'),
    path('davomat-false/<int:pk>/', Davomat_False, name='davomat-false'),
    path('outgoings/', All_Outgoings, name="all-outgoings"),
    path('send/message/parent/all/', Send_All_Parents, name="send-message-parent-all"),
    path('attendance/monthly/<int:pk>/', Attendance_Monthly, name='attendance-monthly'),
    path('waiting-pupils/', Waiting_Pupils, name="waiting-pupils"),
    path('salleries/all/', All_Salleries, name='all-salleries'),
    path('check/misssed/<int:pk>/', Check_Missed_Lesson, name="check-missed-lessons"),
    path('workplan/<int:pk>/', Work_Plan, name="work-plan"),
    path('workplan/add/', Add_Workplan, name="add-workplan"),
    path('checkout/get/<int:pk>/', Get_Chekout, name="get-checkout"),
    path('<username>/', My_Profile, name="my-profile"),
    #All tests are here
    path('buttons/test', Buttons_Test),
]